# Generated by Django 4.2.13 on 2024-05-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.DateField()),
                ('actor', models.CharField(blank=True, max_length=20, null=True)),
                ('actoress', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
